name: nginx-deployment
on: push
jobs:
 my-job:
   runs-on: Windows
   steps: 
     - name: Checkout
       uses: actions/checkout@v3
     - name: Build Images
       shell: cmd
       run: docker build -t venkateshnarla/demo-git-repo .
     - name: Push Image
       shell: cmd
       run: docker push venkateshnarla/demo-git-repo
     - name: Kubernetes Deployment 
       shell: cmd
       run: kubectl apply -f k8s.yaml
     - name: Test 
       shell: cmd
       run: kubectl get all 

